#!/bin/bash

set -euo pipefail


TARGET_DIR="$(dirname -- "$0")/backup"
TIMEOUT=1

function delete_file() {
    local files=($(find "${TARGET_DIR}" -maxdepth 1 -cmin +"${TIMEOUT}"))

    if [ ${#files[@]} -eq 0 ]; then
        return
    fi

    for item in "${files[@]}"; do
        if [ "${item}" != "${TARGET_DIR}" ]; then
            rm -rf "${item}"
        fi
    done
}

