#!/bin/bash

set -euo pipefail

backup_dir="$(dirname "$0")/backup"

function mk_backup_dir() {
    if [ ! -d "${backup_dir}" ]; then
        mkdir "${backup_dir}"
        echo "Make directory at ${backup_dir}"
    fi
}

function copy_file() {
    mk_backup_dir

    local file_path="$1"
    local filename="$(basename "${file_path}")"
    cp "${file_path}" "${backup_dir}/${filename}"
}

function remove_file() {
    local args=("$@")
    local target="${args[${#args[@]} - 1]}"
    local rm_cmd="$(which rm)"
    
    copy_file "${target}"

    "${rm_cmd}" "${args[@]}"
}

remove_file "$@"
