#!/bin/bash

set -euo pipefail

BACKUP_DIR="$(dirname -- "$0")/backup"

function mk_backup_dir() {
    if [ ! -e "${BACKUP_DIR}" ]; then
        mkdir "${BACKUP_DIR}"
        echo "Make directory at ${BACKUP_DIR}"
    fi
}

function remove_file() {
    local date=$(date +%y%m%d_%R:%S)

    for item; do
        if [ "${item}" = "--" ]; then
            continue
        fi

        local file=$(basename -- "${item}")
        local dir=$(dirname -- "${item}")
        mv -- "${dir}/${file}" "${BACKUP_DIR}/${file}_${date}"
    done
}

mk_backup_dir
remove_file "$@"
