#!/bin/bash

set -euo pipefail


function show_help() {
    echo "Usage: $0 [file ...]"
    echo "This command backs up the specified files and deletes them."
}

if [ "$#" -le 0 ]; then
    echo "Error: Missing arguments."
    show_help
    exit 1
elif [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    show_help
    exit 0
fi


BACKUP_DIR="$(dirname -- "$0")/backup"

function mk_backup_dir() {
    if [ ! -e "${BACKUP_DIR}" ]; then
        mkdir "${BACKUP_DIR}"
        echo "Make directory at ${BACKUP_DIR}"
    fi
}

function remove_file() {
    local date=$(date +%y%m%d_%R:%S)

    for item; do
        if [ "${item}" = "--" ]; then
            continue
        fi

        local file=$(basename -- "${item}")
        local dir=$(dirname -- "${item}")
        mv -- "${dir}/${file}" "${BACKUP_DIR}/${file}_${date}"
    done
}


mk_backup_dir
remove_file "$@"
