#!/bin/bash

set -euo pipefail


function show_help() {
    echo "This command backs up the specified files and deletes them."
    echo "Usage: $0 [file ...]"
    echo "  or   $0 [option]"
    echo "Options:"
    echo "  --help, -h  Display this help massage."
    echo "  start       Start a process to automatically delete old backups."
    echo "  stop        Stop the above process."
}


NOHUP_PID_FILE="$(dirname -- "$0")/.pid"

if [ "$#" -le 0 ]; then
    echo "Error: Missing arguments."
    show_help
    exit 1
elif [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    show_help
    exit 0
elif [ "$1" = "start" ]; then
    if [ -f "${NOHUP_PID_FILE}" ]; then
        echo "The process is already running."
        exit 1
    fi
    nohup ./delete_old_files > /dev/null &
    echo "$!" > "${NOHUP_PID_FILE}"
    exit 0
elif [ "$1" = "stop" ]; then
    if [ ! -f "${NOHUP_PID_FILE}" ]; then
        echo "Process is not running."
        exit 1
    fi

    pid="$(cat "${NOHUP_PID_FILE}")"
    kill -TERM "${pid}"

    rm "${NOHUP_PID_FILE}"
    echo "Stoped process."
    exit 0
fi


BACKUP_DIR="$(dirname -- "$0")/backup"

function mk_backup_dir() {
    if [ ! -d "${BACKUP_DIR}" ]; then
        mkdir "${BACKUP_DIR}"
        echo "Make directory at ${BACKUP_DIR}"
    fi
}

function move_file() {
    local date=$(date +%y%m%d_%R:%S)

    for item; do
        if [ "${item}" = "--" ]; then
            continue
        fi

        local file=$(basename -- "${item}")
        local dir=$(dirname -- "${item}")
        mv -- "${dir}/${file}" "${BACKUP_DIR}/${file}_${date}"
    done
}


mk_backup_dir
move_file "$@"
